version: "3"

services:
  db:
    env_file: ./.env
    image: mysql
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}