version: "3"

services:
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
  
  api:
    build: .
    container_name: api
    restart: always
    command: npm start
    env_file:
     - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/app"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"