version: "3"

services:
  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      DATABASE_HOST: db
  
  api:
    build: .
    container_name: api
    restart: always
    command: npm start
    env_file:
     - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/app"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"